[metadata]
name = phrefine
version = 0.1
description = gibbs energy correction for phase diagram
author = wenhao Zhang
author_email = ZHANG.Wenhao@nims.go.jp

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    torch
    pycalphad
    rich
    numpy
    scipy
    
[options.packages.find]
where = src